replicaCount: 1

image:
  repository: vsmetgud/media-portal
  tag: "bf2bc53a9e992ce41001f7a9fb12d08995e5062b"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080

persistence:
  enabled: true
  mountPath: /usr/share/nginx/html/media
  hostPath: /media/sf_e-drive

ingress:
  enabled: false
  className: nginx
  host: vsmetgud.buzz

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector:
  kubernetes.io/hostname: k8s-worker

autoscaling:
  enabled: false
