replicaCount: 1

image:
  repository: vsmetgud/media-portal
  tag: "462b3dc4805281c40368e27185b89d1e6386c239"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080

persistence:
  enabled: true
  mountPath: /usr/share/nginx/html/media
  hostPath: /media/sf_e-drive

ingress:
  enabled: false
  className: nginx
  host: vsmetgud.buzz

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector:
  kubernetes.io/hostname: k8s-worker

autoscaling:
  enabled: false
