replicaCount: 1

image:
  repository: vsmetgud/media-portal
  tag: "dcbfb8d21674cc330cd838fd005c03bbdb1a449b"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30050

persistence:
  enabled: true
  mountPath: /usr/share/nginx/media
  hostPath: /media/sf_e-drive

ingress:
  enabled: false
  className: nginx
  host: vsmetgud.buzz

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector:
  kubernetes.io/hostname: k8s-worker

autoscaling:
  enabled: false
