replicaCount: 1

image:
  repository: vsmetgud/media-portal
  tag: "791f4244023495fc4f8a20755bbe1c82df5442a2"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080

persistence:
  enabled: true
  mountPath: /usr/share/nginx/html/media
  hostPath: /mnt/media

ingress:
  enabled: false
  className: nginx
  host: vsmetgud.buzz

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector:
  kubernetes.io/hostname: k8s-worker

autoscaling:
  enabled: false
